version: "3"

dotenv:
  - ".env"

tasks:
  build/rpc:
    cmds:
      - protoc -I=./rpc --go_out=paths=source_relative:./rpc rpc/propolis/v1/*.proto


  run/pub:
    cmds:
      go run main.go fed --host localhost --port 9000